jwt:
  secret: 1a0976dbfba31cfb41f8544e61b7807f9c90dd593f06ff52dc3c21b34f3673d8
  lifetime: 30m
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/task_db
    username: root
    password: 1234
logging:
  level:
    org.springframework.security: DEBUG